name: PaxFlags
version: 1.0
main: com.paxflags.PaxFlagsPlugin
api-version: 1.21
author: PaxMC
description: Territory conquest plugin for PaxMC
commands:
  town:
    description: Create or manage your town
    usage: /town <create|info|delete> [name]
  placeflag:
    description: Place a flag to claim land
    usage: /placeflag
permissions:
  paxflags.town.create:
    description: Allows player to create a town
    default: true
  paxflags.placeflag:
    description: Allows player to place flags
    default: true
